### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reView#27]
**Bug Description**
Receiving this error when reading both chart and map table. Possibly due to moved cached folder. Breaks completely in debug mode, but some sort of exception handler in production reloads the file and it works, though the error is still thrown.

**Full Traceback**
```Traceback (most recent call last):
  File "/Users/twillia2/github/reView/reView/utils/classes.py", line 181, in _callback_func
    return func(*args, **kwargs)
  File "/Users/twillia2/github/reView/reView/pages/rev/controller/callbacks.py", line 764, in figure_chart
    dfs = cache_chart_tables(signal_dict, region)
  File "/Users/twillia2/anaconda3/envs/review/lib/python3.9/site-packages/flask_caching/__init__.py", line 834, in decorated_function
    cache_key = decorated_function.make_cache_key(f, *args, **kwargs)
  File "/Users/twillia2/anaconda3/envs/review/lib/python3.9/site-packages/flask_caching/__init__.py", line 591, in make_cache_key
    fname, version_data = self._memoize_version(
  File "/Users/twillia2/anaconda3/envs/review/lib/python3.9/site-packages/flask_caching/__init__.py", line 541, in _memoize_version
    version_data_list = list(self.cache.get_many(*fetch_keys))
  File "/Users/twillia2/anaconda3/envs/review/lib/python3.9/site-packages/cachelib/base.py", line 49, in get_many
    return [self.get(k) for k in keys]
  File "/Users/twillia2/anaconda3/envs/review/lib/python3.9/site-packages/cachelib/base.py", line 49, in <listcomp>
    return [self.get(k) for k in keys]
  File "/Users/twillia2/anaconda3/envs/review/lib/python3.9/site-packages/flask_caching/backends/filesystemcache.py", line 120, in get
    pickle_time = pickle.load(f)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3: invalid start byte
```

**Comment by WilliamsTravis** [comment]
This was a cache problem....fixed by storing the cache consistently in ~/.review
